### ISSUE TITLE
Global word-wrap doesn't render correctly with this VS-Code extension

### ISSUE THREAD

**Issue by ennoweichert** [asciidoctor/asciidoctor-vscode#172]
I have word-wrap set to:

```json
    "editor.wordWrap": "wordWrapColumn",
    "editor.wordWrapColumn": 80,
```

This setting works for me.

But it does not for any file that is configured as AsciiDoc with this VS-Code extension, no matter the filename extension and no matter if automatically detected or manually set.

I gave [bcherny/better-asciidoctor-vscode](https://github.com/bcherny/better-asciidoctor-vscode) a cursory look and it seems to render word-wrap as expected.

I have not given this much attention so I have no further technical explanation.

**Comment by MatteoCampinoti94** [comment]
It's not a bug.

AsciiDoc is a markup language, so there is a language-specific setting that enables wordWrap to viewport, superseding the global value.
```JSON
"[asciidoc]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": false
    }
```

You can force it to use global setting by declaring it as empty:
```JSON
"[asciidoc]": {}
```

Or you can set it to any value you want, and even add other settings to it. For example these are the settings I use.
```JSON
"[asciidoc]": {
        "editor.quickSuggestions": true,
        "editor.wordWrap": "bounded",
        "editor.fontLigatures": false,
        "editor.renderIndentGuides": false
    }
```

You can also add other settings, as long as `editor.wordWrap` is not declared under `[asciidoc]` then it'll use the global value.

These default settings will not be changed, they are there to ensure markup languages are rendered with at least some word wrapping which is otherwise disabled by default.
