### ISSUE TITLE
Cite doesn't work correctly when using asciidoctor.js

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor-vscode#173]
Hello!

Minimal working example:

```
= Test document
:nofooter:
:c: 0

Some long text [<<cite-1>>]. Other text [<<cite-2>>].

++++
<style>
    body {background-color:white;color:rgba(0,0,0,0.8)}
</style>
++++

== Bibliography

. [[cite-1,{counter:c}]]
    Cite 1.

. [[cite-2,{counter:c}]]
    Cite 2.
```

When `use asciidoctor.js` is checked:

![image](https://user-images.githubusercontent.com/33900895/54803239-c0c1e180-4c7f-11e9-9c51-769d41513d47.png)

When I use Ruby version of Asciidoctor (`use asciidoctor.js` is unchecked):

![image](https://user-images.githubusercontent.com/33900895/54803302-04b4e680-4c80-11e9-9aff-422692a497e5.png)

-- Andrey.

**Comment by MatteoCampinoti94** [comment]
We do not maintain asciidoctor.js, sorry.

We use asciidoctor.js as default processor only because it can bundled with the extension, whereas the Ruby one needs to be manually installed on the system.

I'm working on changing the way the extension feeds the source text to the processor, but it most likely won't solve these kind of problems.

Sorry for not being able to help.

**Comment by sindzicat** [comment]
If I understood correctly I was mistaken with the repo.
Now my question is here: https://github.com/asciidoctor/asciidoctor.js/issues/701
