### ISSUE TITLE
Support syntax highlighting for regular (non-fenced) blocks

### ISSUE THREAD

**Issue by behrangsa** [asciidoctor/asciidoctor-vscode#212]
E.g:

```
[source,js]
----
let x = 1;
----
```

This is related to #153.

**Comment by danyill** [comment]
Looking at how to resolve this issue made me ask, "What is the most mature TextMate grammar for Asciidoc?"

Currently that I am aware of:

* [Christian Zuckschwerdt for TextMate ?1?](https://github.com/zuckschwerdt/asciidoc.tmbundle) (`plist`) based on Python Asciidoc and seems to have originated about 2008.

* [Matt Neuberg for TextMate 2](https://github.com/mattneub/AsciiDoc-TextMate-2.tmbundle) (`plist`). Developed in 2014 to meet the needs of TextMate 2 which the Zuckschwerdt bundle didn't do especially well, deliberately doesn't cover setext headers well or nested lists or various multi-line constructs as they are difficult to do in TextMate languages (single line at a time regexes). Still maintained.

* [SublimeText 3 bundle based on the Neuberg bundle, created by Jakub Jirutka](https://github.com/asciidoctor/sublimetext-asciidoc) (`YAML`). Converted to `YAML` from which a `plist` is generated.
   
* The [Atom package maintained by Ludovic Fernandez](https://github.com/asciidoctor/atom-language-asciidoc/) (`CSON`). Started about 2014. Although Atom has moved beyond TextMate grammars to [Tree-sitter](https://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/)grammars. Has had some contributions by Dan Allen and seen some improvements. Originally appears to have been based on the TextMate grammar and then this was abandoned and a new grammar was created.

The grammar used for this extension is based off the SublimeText 3 bundle.

Of the above, the Atom package seems to have been the most developed and supported. It seems (to me) to be more sophisticated to allow the support of complex items (like the `source` code block).

I used the npm package [cson](https://www.npmjs.com/package/cson) to convert this from `cson` to `json`, changed the scopeName from `source.asciidoc` to `text.asciidoc` and updated the `package.json` to use the `json` language form.

With these fairly modest changes, from what I can tell this grammar works perfectly fine within this extension although it has quite different semantics. If this was an acceptable approach for this extension, it would allow this issue to be closed.

The alternative approach of trying to change the current syntax highlighting to support the source block is somewhat complex (we need to distinguish several different types of blocks and TextMate only allowing single line regexes makes this difficult). My initial attempts showed significnt changes would be required to the existing grammar and I would prefer to rely on and leverage the broader Asciidoctor ecosystem if possible.

We might want to see if there were any plans to move away from the TextMate langauge for Atom before we decided on this.

Anyway, I guess I propose we manually update the language periodically from:

https://github.com/asciidoctor/atom-language-asciidoc/blob/master/grammars/language-asciidoc.cson

I'll do a PR for discussion in case anyone wants to compare before/after.

@MatteoCampinoti94 has made most of the improvements to the syntax highlighting since this was taken from SublimeText and might have a well informed opinion?

This will mean that for instance #248 may be re-opened and we may need to contemplate the pros and cons of sticking strictly to upstream to reduce maintenance.

**Comment by MatteoCampinoti94** [comment]
@danyill the syntax highlighting used by the extension does support multi-line regex via the `(?x)` flag. However, I agree that the using the syntax from the atom extension is a good idea. It seems to work better and it is much easier to deal with than the old one.

And thanks for the pull 👍

**Comment by danyill** [comment]
Thanks @MatteoCampinoti94 

According to https://github.com/Microsoft/vscode-textmate/issues/32 multi-line syntaxes are disallowed....

**Comment by MatteoCampinoti94** [comment]
@danyill that's weird, some of the syntax I wrote used multiline, for example to recognize tables and source blocks
