### ISSUE TITLE
Can't make colored text work

### ISSUE THREAD

**Issue by sgandon** [asciidoctor/asciidoctor-vscode#227]
I am not sure if it is a bug or a feature request.

## Description
using 
```
[red]#foo#
```
Should render in red the word foo but it does not.
looking at the ref here : https://www.methods.co.nz/asciidoc/chunked/ch10.html

## System Information
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

AsciiDoc 0.0.3
## To Reproduce
create a adoc file with 
```
[red]#foo#
```
open the renderer and notice it is not red

**Comment by FatihBozik** [comment]
Hi @sgandon,

It works perfectly on my machine. I think you're using the wrong plugin. [AsciiDoc plugin](https://marketplace.visualstudio.com/items?itemName=joaompinto.asciidoctor-vscode) latest version is 2.7.6.

**Comment by sgandon** [comment]
indeed you are right, I wanted to use that in a formated paragraph with (2 spaces at the start of the line) but there is fails. I will have to find another way.
Thanks for your answer.

**Comment by danyill** [comment]
@sgandon you could try something like this:

```asciidoc
[.red]
--
{nbsp}{nbsp}This is a paragraph which is in red. It's inside an open block `--` and can have multiple sentences with spaces separated.

Like this.
--
```

![image](https://user-images.githubusercontent.com/674783/74483496-7abadf80-4f1b-11ea-90bd-528e53fbfdc4.png)

There is a list of special attributes in Asciidoc [here](https://asciidoctor.org/docs/user-manual/#charref-attributes), `{nbsp}` is one which won't be "chomped".

Generally if you're wanting to carry out a first line indent in a paragraph you should do this with css in your own stylesheet and possibly a role as this achieves the goal of separating form from content. For the write css, see [this](https://stackoverflow.com/questions/5856952/indenting-only-the-first-line-of-text-in-a-paragraph) and also the Asciidoctor [documentation](https://asciidoctor.org/docs/user-manual/#customizing-your-output) on themes/css

Since this issue is not related to this extension, I'll close it. Feel free to re-open it if this doesn't address your concern adequately.
