### ISSUE TITLE
had to run gem install

### ISSUE THREAD

**Issue by mvolkmann** [asciidoctor/asciidoctor-vscode#235]
I was not able to get the preview feature to work until I ran "gem install asciidoctor" on my Mac. Should that be added to the install instructions?

**Comment by danyill** [comment]
@mvolkmann that would be correct if you had disabled the use of asciidoctor.js in the preferences:

![image](https://user-images.githubusercontent.com/674783/70861217-af4c0280-1f8f-11ea-8601-a538542966fd.png)

If the tick box is there then either the Ruby or Java runtime is not necessary because the Javascript run time is bundled with the extension.

**Comment by mvolkmann** [comment]
I didn't know that option existed, but I just verified that it is checked. So I don't think I ever had it unchecked.

**Comment by danyill** [comment]
I'm going to close this issue. 

It should not be necessary to run `gem install` out of the box after installing this extension.

I've not needed the ruby gem for Asciidoctor installed on Windows or Linux systems so I think this must be either a setting or an environment issue. If it was a widespread problem I expect we would be getting frequent reports of it...
