### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jpsinnott** [asciidoctor/asciidoctor-vscode#250]
- Issue Type: `Performance`
- Extension Name: `asciidoctor-vscode`
- Extension Version: `2.7.8`
- OS Version: `Darwin x64 19.2.0`
- VSCode version: `1.41.1`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by danyill** [comment]
Thanks for reporting. Can you provide some specific details, is it high load:

* only with the preview window open?
* during opening of a file?
* only for large files (how many lines?)?
* only during typing?

Because the preview is rendered constantly while typing I would expect CPU to go up if you have the preview open. We could look into making the preview refresh time customizable by the end user (obviously the preview would be less up-to-date).

During typing there is constantly the preview, the outline view and the syntax highlighting being updated. Asciidoctor does not generate a "partial preview" so for large documents this will increase CPU usage if we provide a fast refresh to the end user but I guess there are various strategies for throttling and controlling it.

What is the impact on you of the high CPU usage? Is it locking up VS Code? Your desktop? Is it only "laggy/slow" is it a delay between pressing a key and seeing text on-screen?

**Comment by danyill** [comment]
Closing due to lack of response.

Feel free to re-open this if you'd like to continue this conversation. 

I'm confident improvements can be made in this area but I think they need to be targeted against the specific problem which is being experienced.
