### ISSUE TITLE
Paste image on linux fails

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#255]
## Description

When pasting images on Linux (Kubuntu 19.10) I receive an error message and no image appears.

## System Information

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-24-generic

## To Reproduce

On Linux use the Paste Image command

## Screenshots & Files

![image](https://user-images.githubusercontent.com/674783/73575409-01fc6200-44dd-11ea-8a94-f5d08aa1c870.png)

**Comment by joaompinto** [comment]
Currently power shell is explicitly used https://github.com/asciidoctor/asciidoctor-vscode/blob/master/src/image-paste.ts#L69. 

I will do some research, a proper fix would be to re-implement with some js library, if that turns out  to be too complex I will probably use some Linux CLI as a workaround.

**Comment by joaompinto** [comment]
I guess multi-platform clipboard access directly from JS would be rather complex. I found a good case with external scrip support for Linux/Mac/Windows:
https://github.com/telesoho/vscode-markdown-paste-image/blob/master/src/paster.ts#L571

Will wok on this on a new branch:
https://github.com/asciidoctor/asciidoctor-vscode/tree/cross-platform-image-paste
