### ISSUE TITLE
Let's save folding provider (simpler regex parser required)

### ISSUE THREAD

**Issue by aur3l14no** [asciidoctor/asciidoctor-vscode#275]
My points are 1) Folding providers are necessary 2) A simpler regex parser should be implemented.

I think folding is very useful because it helps users gain an outline of the document. At least the folloing should be provided in folding ranges:

- Sections outlined by headings (already implemented correctly)
- Source code blocks

Currently folding provider codes are commented out because they are **1) laggy 2) not correctly implemented**.

The latter is easy to solve. `getHeaderFoldingRanges` already works, and simply removing `getRegionFoldingRanges` and `getBlockFoldingRanges` would do. Providing ranges for source code blocks is also easy if we use the asciidoctor.js.

However **latency** is a bit harder to address.

Folding providers are very performance-sensitive. If latency is high, then the folded sections would be automatically unfold in VSCode. You cannot use the technique for symbol provider in here. Thus a simpler parser is definitely needed to implement the folding provider.

In #238, @danyill considered using a **simple regex parser** to replace a full-functional parser in (at least) toc, symbol, folding providers. I think it would really help improve performance in many functions. Maybe we should discuss about it.

**Comment by danyill** [comment]
Thanks for your thoughts @aur3l14no 

The folding provider is only commented out at the moment because other code changes which used the same functions had a poor effect on the outline provider and because it was non-functional anyway (a hang over from the markdown extension this was based off). 

I think if can find a little time to work through the code we could get this working again. I'm keen to using folding as well.

Whether we should be using a simpler regex based parser or taking the output from the Asciidoctor converter I'm not sure. I'm keen to try to use the Asciidoctor parser first and if that becomes problematic we could then look at other solutions.

At the moment in this extension we call the parser too frequently. Where that's become a problem we've throttled the calls which seems to have provided acceptable performance for most people. Ultimately we need to implement something like a queuing or event based system where the output from parsing becomes available to commands and features without each feature executing the parser. That would require some architecture and development effort and would fit in well with moving the extension to the preferred [language server model](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) which I haven't found time to look into yet.

**Comment by danyill** [comment]
Since this feature request already exists on a previous open issue, I'll close this in favour of #70
