### ISSUE TITLE
eslint

### ISSUE THREAD

**Issue by larshp** [asciidoctor/asciidoctor-vscode#290]
Hi,
Great extension, thanks

I'm reading through some of the code, like
https://github.com/asciidoctor/asciidoctor-vscode/blob/master/src/asciidocEngine.ts#L57
and noting that the whitespace is not consistent, sometimes there are tabs, some spaces.

Any thoughts on setting up eslint(with typescript plugin, tslint is deprecated) to enforce conventions regarding whitespace?

**Comment by danyill** [comment]
@larshp thanks for filing this issue -- you're spot on, we need to be adding CI to enforce style and have some sane eslint defaults included in this repo. We've got a bit of technical debt in this repo because much of the development brought together pre-existing things from other projects.

I'm happy to take a PR or I'll hope to get to this eventually. It probably can't all be done automatically so it may take a little while to work through the changes.

I'd like to use a `.eslintrc` something like:

```json
{
  "extends": "standard",
  "rules": {
    "arrow-parens": ["error", "always"],
    "comma-dangle": ["error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline"
    }],
    "max-len": ["error", {
      "code": 120,
      "ignoreStrings": true,
      "ignoreUrls": true,
      "ignoreTemplateLiterals": true
    }],
    "spaced-comment": "off"
  }
}
```

But I'm open to suggestion.

**Comment by larshp** [comment]
Thanks

PR https://github.com/asciidoctor/asciidoctor-vscode/pull/291 opened with basic setup

Follow up steps:
* Enable github actions, should at least run the "compile" and "lint" scripts
* Enable additional rules

**Comment by larshp** [comment]
ref #292

**Comment by danyill** [comment]
@larshp thank you so much for this. Looks great and gets us started with CI. I think @joaompinto has enabled Github Actions (thanks) so can we now close this issue?

**Comment by larshp** [comment]
I'd like to also enable the rule for indentation, do you prefer spaces or tabs?

**Comment by danyill** [comment]
Spaces please.
