### ISSUE TITLE
Align the "Export to PDF" to  the "Save as HTML" user experience

### ISSUE THREAD

**Issue by CWempe** [asciidoctor/asciidoctor-vscode#298]
As a beginner, I am currently experimenting to create a nice theme for my project.
Therefore I constantly use the `AsciiDoc: Export document as PDF´ (asciidoctor-pdf) command in vscode.
But every time I have to confirm to overwrite the existing pdf and click "open file" in the upcomming notification.
This is kind of annoying and time consuming.

I would like to be able to set the following options as user or workspace settings in vscode:

* ask for filename : true/false
  * false: use the original filename of the document and add `.pdf`  
* overwrite file by default: true/false
* automatically open generated pdf: true/false

**Comment by danyill** [comment]
Thanks for the suggestion @CWempe I'd be happy to take a PR for this or I'll put it in the backlog. 

With the "Save to HTML" feature I didn't support a user-entered filename for the html to improve the feedback loop but since it's there for the pdf I'd be reluctant to remove it.

It may not be easy to do the last option portably while avoiding the poor user experience of opening many pdfs open simultaneously in the pdf viewer. 

I'd suggest it might be better to do the first two and achieve the desired outcome of the third using a pdf viewer which will automatically reload the pdf on changes (e.g. evince)

**Comment by CWempe** [comment]
I am not a developer.
So I would appreciate it if you would add this to the backlog. :)

Tanks.

**Comment by joaompinto** [comment]
The "Save to HTML" is less disruptive, I will change Export to PDF for the same behavior.

**Comment by joaompinto** [comment]
I am closing this issue because it was associated with a failed attempt to provide the desired function which reverted after unplanned issues.

I have create the new issue  https://github.com/asciidoctor/asciidoctor-vscode/issues/333 , by supporting the settings at the document level the extension it will allow the automation behavior requested on this issue.

Thanks
