### ISSUE TITLE
Suport for docfile, docfilesuffix, docname attributes

### ISSUE THREAD

**Issue by GauntletPL** [asciidoctor/asciidoctor-vscode#316]
Using {docfile}, {docfilesuffix} or {docname} attributes defined in official asciidoctor manual (https://asciidoctor.org/docs/user-manual/#env-attributes) does not produce any results. At the same time {docdir} works perfectly fine.

![image](https://user-images.githubusercontent.com/42208078/82072200-98910f80-96d7-11ea-9e9f-f3dee7dddbde.png)

![image](https://user-images.githubusercontent.com/42208078/82072286-c5452700-96d7-11ea-831a-15997cf87b4a.png)

**Comment by danyill** [comment]
We run Asciidoctor by passing the document [to stdin](https://asciidoctor.org/docs/user-manual/#piping-content-through-the-cli) not writing to the filesystem which is why these attributes don't appear (and so you can have a preview without saving your file)

That's not to say that we can't set them when we call the processor though, it's a fairly simple change.

**Comment by danyill** [comment]
We get `docdir` because we [explicitly set](https://github.com/asciidoctor/asciidoctor-vscode/blob/f0ecdb1f19b63ed110434f8eaa1e66417ee448bf/src/text-parser.ts#L106) `base_dir`.
I'll do a PR for this.

**Comment by albertschulz** [comment]
I would highly appreciate this feature.
Is there maybe any reference from VSCode, in case the text originates from a file?

**Comment by ggrossetie** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor-vscode/pull/872

**Comment by albertschulz** [comment]
> Fixed in #872

This is great! Thank you <3
