### ISSUE TITLE
Mermaid diagram is not working with kroki docker

### ISSUE THREAD

**Issue by edl7878** [asciidoctor/asciidoctor-vscode#323]
Kroki docker container can generate mermaid diagram.

But, asciidoctor-vscode can't get it.

**Comment by aloyse** [comment]
I'm using [yuzutech/kroki](https://cloud.docker.com/u/yuzutech/repository/docker/yuzutech/kroki) docker-compose with the fellow yuzutech/kroki-mermaid and yuzutech/kroki-blockdiag containers
* vscode-asciidoc **works fine** with ":kroki-server-url: http://mykrokicontainer" for the following diagrams
  * blockdiag (via yuzutech/kroki-blockdiag container)
  * ditaa
  * graphviz
  * plantuml

* unfortunately the **mermaid diagrams are not rendered** 
(I did successfully test my krokicontainer with the generated urls from [kroki.io/#try](https://kroki.io/#try for mermaid rendering)

* i noticed that the formating of the mermaid diagrams is plain html...
( ? perhaps due to src/text-parser.ts line 18: asciidoctor.Extensions.register(function... )

**Comment by danyill** [comment]
Thanks for reporting @edl7878 and for your diagnosis @aloyse. I think the most recent release (2.7.16) will have fixed this. Previously mermaid diagrams were handled specially (I'm not sure why) but this code has now been removed.

Using the default kroki server I get:

![image](https://user-images.githubusercontent.com/674783/85214574-c0ebe800-b3c0-11ea-9e10-f16b4993d4eb.png)

I think this will be similar using the docker container.
Could you check using the 2.7.16 release please?

**Comment by edl7878** [comment]
I have tested 2.7.16 release, Mermaid is workable.

Thanks.

**Comment by aloyse** [comment]
Thanks for your quick reaction
2.7.16 is showing mermaid diagrams correctly
