### ISSUE TITLE
If :doctype: is book and sectnums is on, cross references autogen text to a chapter is still "Section"

### ISSUE THREAD

**Issue by DaLynxx** [asciidoctor/asciidoctor-vscode#328]
## Description

For an asciidoc file where the :doctype: is set to book and where sectnums is on, the cross reference autogen text in the resulting link generates "Section" rather than the expected "Chapter".

## System Information
Version: 1.46.0 (user setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-10T09:03:20.462Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Asciidoc extension version: 2.7.15

## To Reproduce

The attached asciidoc (txt) file (IssueInVSCodePlugin.txt):

Renders as
![image](https://user-images.githubusercontent.com/1823630/84988498-62b1d180-b142-11ea-8b4b-1800eef1921d.png)
 
in asciidoctor v2.0.10 and in the Asciidoctor.js live preview firefox extension version 2.4.1

but as 

![image](https://user-images.githubusercontent.com/1823630/84988776-e2d83700-b142-11ea-8e60-6577ed5cc19c.png)

in VSCode.

Note the difference between the "Chapter 1" and "Section 1" link text for reference 1.

## Screenshots & Files

[IssueInVSCodePlugin.txt](https://github.com/asciidoctor/asciidoctor-vscode/files/4796813/IssueInVSCodePlugin.txt)

**Comment by danyill** [comment]
@DaLynxx you are correct, thanks for reporting. That is also the behaviour I see.

At the moment this extension passes to Asciidoctor.js a set of options, one of which defines the doctype as article. This will override any option selected by the user.

https://github.com/asciidoctor/asciidoctor-vscode/blob/976bce20b45c637888843ffe23388383a878e1d5/src/text-parser.ts#L91-L99

I'm not sure why we do this -- it seems unnecessary to me however the fix is straightforward. We'll see if anyone remembers why it's like this and then I can do a PR to remove this option.

**Comment by Mogztter** [comment]
Will be fixed by https://github.com/asciidoctor/asciidoctor-vscode/pull/418

**Comment by Mogztter** [comment]
Should be fixed, please reopen if that's not the case.
