### ISSUE TITLE
Support coderay, prettify, pygments and rouge source-highlighting schemes

### ISSUE THREAD

**Issue by vbansal22** [asciidoctor/asciidoctor-vscode#373]
Only scheme currently supported is highlightjs

**Comment by LuciaFe** [comment]
I need it also

**Comment by Mogztter** [comment]
Pygments is written in Python (with a Ruby binding https://github.com/pygments/pygments.rb), CodeRay and Rouge are written in Ruby.

VS Code extensions are running in Node.js environment. We can support additional _JavaScript_ syntax highlighters but unless someone port CodeRay, Rouge or Pygments to JavaScript we cannot use them.

If you really want to use them, then you should the `asciidoctor` CLI.

Since this issue is out-of-scope, I will close it but feel free to open a new issue to request support for Prism.js (and please create one issue per syntax highlighter since it's way easier to track progress)
