### ISSUE TITLE
.asciidoctorconfig

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-vscode#380]
When I work with included subdocuments, I often face the problem that the preview can't find my images. 
This is because I set the `:imagesdir:` in the main `.adoc`-File and the included document can't give the preview a hint about this.

A nice solution can be found here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

A file called `.asciidoctorconfig` which will be prepended for the preview. This gives you the chance to tell the preview about the correct `imagesdir` and all images will be displayed.

**Comment by bovinemagnet** [comment]
I like this idea, however, can I ask how this is different from including a `_attributes.adoc` file, as this seems to be the common way to do this (I know it is troublesome).

I like it, because it might solve the issue I have with my workflow, which is, I edit with vs-code using asciidoctor-vscode , and publish with Antora, and asciidoc-pdf. 

The two things that stand out to me though are if it is included like it is shown in the example, as a straight `include::` then it feels no different from an `include::_attributes.adoc[]` type approach  (the example is  `include::.asciidoctorconfig[]`)

The second bit, I like, is that there can be more than one existing, I guess if It worked more like a `.gitignore`, where it could  overrides at that point?

So if I think about my workflow, where would the you have an antora project structure such as the following.  There is the opportunity to have the file live within the pages directory (feels like it would have the same issues as I currently face with the `_attributes.adoc` approach), or probably more usefully in each of the specific module directories (ROOT, api, etc).

`
modules\
 ROOT\
   .asciidoctorconfig
   pages\
       .asciidoctorconfig
   partials
   images
api\
   .asciidoctorconfig
   pages\
      .asciidoctorconfig
   partials
   images  
`

**Comment by thammegowda** [comment]
I used `.asciidoctorconfig` to insert some CSS style for HTML preview,
```adoc
ifdef::backend-html5[]
++++
<style>
body {
font-family: "Linux Libertine O", "Helvetica"
}

h1, h2, h3, h4, h5 {
font-family: "Linux Libertine O", "Helvetica"
}
</style>
++++
endif::backend-html5[]
```

this `<style>` tag seems to be inserted before the Level 0 header/title, and it inturn causes
the issue discussed here: https://github.com/asciidoctor/asciidoctor.js/issues/358#issuecomment-317235779 


<img width="520" alt="Screen Shot 2021-11-14 at 2 30 54 AM" src="https://user-images.githubusercontent.com/1865964/141677274-9d05bef5-7e50-4c84-b53c-fa6382e7a1d9.png">

**Comment by rdmueller** [comment]
@thammegowda interesting that this warning does not pop up without the `.asciidoctorconfig`. But the warning seems to be correct and it also pops up if you add some more lines before your first title.

you can avoid it by adding a 

    :doctype: book

before your title or even in your `.asciidoctorconfig`.

hope this helps

**Comment by apupier** [comment]
Current state:
* Support of .asciidoctorconfig file at root of the workspace merged in master branch
* [PR](https://github.com/asciidoctor/asciidoctor-vscode/pull/646) provided for support of .asciidoctorconfig.adoc file at root of the workspace
* [Draft PR](https://github.com/asciidoctor/asciidoctor-vscode/pull/647) in progress for support recursively the .asciidoctorconfig file
* TODO:
  * At the beginning of each of the files, append `:asciidoctorconfigdir:` , this comes in handy to setup for example an `imagesdir`
  * Potentially provide a cache mechanism to avoid reading config file every time

**Comment by apupier** [comment]
Current state:
* Support of .asciidoctorconfig and .asciidoctor.adoc file at root of the workspace merged in master branch
* At the beginning of each of the files, append `:asciidoctorconfigdir:` , this comes in handy to setup for example an `imagesdir`.
* [PR](https://github.com/asciidoctor/asciidoctor-vscode/pull/647) for support recursively the .asciidoctorconfig file is ready to be reviewed.

TODO:
  * Potentially provide a cache mechanism to avoid reading config file every time. Not detected performance issue with my small use case so far.

**Comment by apupier** [comment]
Unless I forgot something, we have reached the same level of support than in IntelliJ.

A point to watch is if there is a performance issue. In this case, we could provide a cache mechanism to avoid reading config file every time. Not detected performance issue with my small use case so far. I think that we can open another issue if we observe that.

@Mogztter How release of new version is planned? Do you have an idea when this feature will be available?
Do we have official "snapshot" extensions that can be tried? I can try to find some people in my organization to do some testing on it.

**Comment by sturtison** [comment]
This is a very nice feature and have just used it. Thank you to the contributors.

.asciidoctorconfig really helps to set up a repeatable, multi-IDE functional preview for people who are foundation level AsciiDoc users and use it on a casual basis. It also helps lower the bar for project adoption.

**Comment by ggrossetie** [comment]
Thanks for your feedback @sturtison !

@apupier I didn't mention it but I've released a new pre-release version. Please give it a try!
