### ISSUE TITLE
Remove Asciidoctor CLI option for preview rendering

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-vscode#443]
Asciidoctor CLI access requires considerable effort to support and provide feature parity compared to Asciidoctor.js. We can't as easily read information back, use extensions etc. without duplicating effort.  Inevitably, users would like feature parity between the different options.

This issue proposes that the purpose of the preview window should not be to invoke the CLI or use external tools and this feature should be removed.

This has been discussed also in #210 and briefly in #442 previously.

**Comment by Mogztter** [comment]
> This has been discussed also in #210 and briefly in #442 previously.

I found at least 2 arguments for keeping this option:

- Being able to use Asciidoctor Diagram (Ruby extension): https://github.com/asciidoctor/asciidoctor-vscode/issues/210#issuecomment-760928079
- Being able to use Rouge syntax highlighter (instead of Highlight.js): https://github.com/asciidoctor/asciidoctor-vscode/issues/210#issuecomment-839146493

> This issue proposes that the purpose of the preview window should not be to invoke the CLI or use external tools and this feature should be removed.

👍🏻 

As an alternative, it's possible to setup a similar workflow using both the [HTML Preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) and [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) extensions to get a live preview using the Asciidoctor CLI.

Here's an example:

![asciidoctorcli](https://user-images.githubusercontent.com/333276/133206915-ddc4a992-503b-4324-9624-3ec834c8cc05.gif)

As you can see, I'm using HTML Preview to preview the HTML produced by the Asciidoctor CLI. And here's the settings.json for the "Run on Save" extension:

```json
{
    "terminal.integrated.shell.linux": "/bin/zsh",
    "javascript.format.semicolons": "remove",
    "typescript.format.semicolons": "remove",
    "editor.tabSize": 2,
    "extensions.ignoreRecommendations": true,
    "liveshare.presence": true,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.adoc$",
                "cmd": "asciidoctor ${file}"
            },
        ]
    }
}
```

You can also setup a workflow *outside* of VS Code that relies on the `asciidoctor` CLI.

It would be interesting to collect feedback from users that are currently using the Asciidoctor CLI through the VS Code extension before removal.

I also believe that this is one thing that prevents us from behind available on VS Code Web (see: #429)


//cc @SjoerdV @DaLynxx could you please give us your opinion?

**Comment by joaompinto** [comment]
I have considered this removal a long time ago, in my opinion the effort of maintaining the CLI option is hardly justifiable having in consideration:

- Maintaining the CLI option usable is a significant effort
- Making the CLI option on pair with the JS version would be a huge effort
- Users which are able to install the CLI most likely will be able to find an alternative flow, as @Mogztter did :)
- Subjective: It's better to provide one good option for most of the users than trying to provide one good option for all the users :)

**Comment by SjoerdV** [comment]
@Mogztter currently I am content enough with the features asciidoctor_js brings. So I really see all the arguments of cutting away the CLI feature that you, @joaompinto and @danyill posed, clearly outweighing the meager benefits of keeping it in.


My current (somewhat shortened) config using Asciidoctor with VSCode is as follows, which is totally workable (except for the code block syntax highlighting in the preview, which is only a slight nuisance)


VSCode 'User' Config for Asciidoc:
```js
//-------- Start Asciidoc Configuration --------
"[asciidoc]": {
	"editor.wordWrap": "on",
	"editor.quickSuggestions": false,
	"editor.fontFamily": "'Fira Code', 'Font Awesome 5 Brands', 'Font Awesome 5 Free', 'Font Awesome 5 Free Solid'", // download: https://community.chocolatey.org/packages/FiraCode	
	"editor.fontLigatures": true,
	"files.trimTrailingWhitespace": false
}
//-------- End Asciidoc Configuration --------
```

VSCode 'Workspace' Config for Asciidoc:
```js
//-------- Start Asciidoc Configuration --------
"asciidoc.use_asciidoctorpdf": true,
"asciidoc.use_asciidoctor_js": true,
"asciidoc.preview.useEditorStyle": false,  
"asciidoc.useWorkspaceRoot": true,
"asciidoc.preview.attributes": {
	"styles": "",
	"imagesdir": "resources/media", 
	"stylesdir": "resources/css", // when use_asciidoctorpdf = false
	"stylesheet": "myworkspace-asciidoc-styles.css" // when use_asciidoctorpdf = false
}  
//-------- End Asciidoc Configuration --------
```

VSCode 'InFile' frontmatter for Asciidoc:
```yml
//-------- Start Asciidoc Configuration --------
// Set Document Properties
:doctitle: XXX
:description: XXX
:author: Sjoerd
:revnumber: A
:revdate: {docdate}
// Path Settings
:imagesdir: ../resources/media
// Set Theme Configuration (used for PDF export)
:pdf-themesdir: ../resources/themes
:pdf-theme: mytheme
// Use Local or Remote Font (Awesome, Web) fonts
:icons: font
// Store data locally on Export
:data-uri:
:allow-uri-read:
// Set Specific Variables
:showtitle:
// Set Syntax Highlighting
:source-highlighter: pygments
:pygments-style: manni
:pygments-linenums-mode: inline
// Enable Section Numbers
:sectnums:
:sectnumlevels: 5
// Set Table of Contents config
:toc: macro
:toclevels: 5
:toc-title: Contents
// Allow Math Expressions
:stem:
//-------- End Asciidoc Configuration --------
```
