### ISSUE TITLE
use local plantuml installation

### ISSUE THREAD

**Issue by BMBurstein** [asciidoctor/asciidoctor-vscode#479]
Is there a way to use a local plantuml (e.g. a command-line tool) instead of starting a plantuml server? I am using this plugin on an offline windows machine, and that would greatly simplify it's usage

**Comment by tigion** [comment]
One way or workaround would be:
1. install the Asciidoctor tools and their dependencies locally
2. configure the Asciidoctor VSCode extension to use the locally installed Asciidoctor instead of the JavaScript variant

Extension settings:
* Asciidoc: Asciidoctor_command: `asciidoctor -r asciidoctor-diagram`
* Asciidoc: Use_asciidoctor_js: `deactivate`

**Comment by mike-stock** [comment]
These configuration options are no longer valid.

Any other solution to this issue?

**Comment by ggrossetie** [comment]
You should use [Kroki](https://github.com/ggrossetie/asciidoctor-kroki) with a document attribute:

```
:kroki-server-url: http://localhost:8080/
```

We won't support Asciidoctor Diagram in the VS Code Extension since we dropped the CLI feature in 3.x. If you want to use Asciidoctor Diagram you can still use it but oustide of the VS Code Extension.
