### ISSUE TITLE
if we use different icons for titles of different levels

### ISSUE THREAD

**Issue by dikinova** [asciidoctor/asciidoctor-vscode#525]
I have a suggestion for the vscode plugin.

if we use different icons for titles of different levels in the outline panel, we will get information about level of titles easily.

for example, if we have an adoc file:

-----

= title1

== title2

=== title3

==== title4

-----

then in the outline panel we show:

------
[a] title1
	[ab] title2
		[abc] title3
			[abcd] title4
		
------

**Comment by Mogztter** [comment]
As far as I know, the outline pane is a built-in feature of VS Code.
At a data level, an outline is a tree of [`DocumentSymbol`](https://vshaxe.github.io/vscode-extern/vscode/DocumentSymbol.html) and the `[abc]` icon depends on the [`DocumentSymbol.kind`](https://vshaxe.github.io/vscode-extern/vscode/SymbolKind.html) attribute.
In this extension, we are using [`SymbolKind#String`](https://vshaxe.github.io/vscode-extern/vscode/SymbolKind.html#String) on all entries because it's the only one that makes sense.

The depth can be inferred from the indentation:

![image](https://user-images.githubusercontent.com/333276/155884472-cf537e97-0346-46b3-b085-509774d06ad3.png)

There's unfortunately nothing we can do to change the layout.
You can open an issue at https://github.com/microsoft/vscode/issues but I doubt they will consider your proposal as the outline is generic (and mostly designed to outline code with classes, methods, fields, constants...)
