### ISSUE TITLE
[Meta] code folding / collapsable sections

### ISSUE THREAD

**Issue by noraj** [asciidoctor/asciidoctor-vscode#570]
## Description

It would be nice to be able to collapse / fold some sections in AsciiDoc documents (like VSCode does for markdown).

## Related issues

- Collapsable sections in editor #360 (about UML diagrams)
- Add code folding on comment blocks #560 (about comment blocks)
- Add code folding based on heading level #70 (about heading level)
- Add code folding on open blocks #553 (about open blocks/panels)

Note: #553 and #70 are closed by b070724cc7030941196f6199687f6ef6415e7787 and 2824561b9c883d67e5acd7cb5776d9f0bfaecd15 but it doesn't seem to work for me. Is that possible there was some regression?

## Similar behavior for Markdown

For example in Markdown document I can fold heading levels or code blocks:

![image](https://user-images.githubusercontent.com/16578570/170838399-ad4cf41d-a4cd-4e8b-a4ad-73c33b777379.png)

Example with title 1 and the code block folded:

![image](https://user-images.githubusercontent.com/16578570/170838433-5546cefb-0ed1-4697-982c-1f42df3b7166.png)

**Comment by Mogztter** [comment]
> Note: https://github.com/asciidoctor/asciidoctor-vscode/issues/553 and https://github.com/asciidoctor/asciidoctor-vscode/issues/70 are closed by https://github.com/asciidoctor/asciidoctor-vscode/commit/b070724cc7030941196f6199687f6ef6415e7787 and https://github.com/asciidoctor/asciidoctor-vscode/commit/2824561b9c883d67e5acd7cb5776d9f0bfaecd15 but it doesn't seem to work for me. Is that possible there was some regression

They are not part of any release, that's why . You can see on the commit page that there's no tag associated:

![commit-without-tag](https://user-images.githubusercontent.com/333276/170880588-6c89ad11-513a-4c2e-8c4c-9a0457725c81.png)

For reference, here's another commit where you can see two tags:

![commit-release](https://user-images.githubusercontent.com/333276/170880589-c811632d-4402-420d-876a-cf251b971227.png)

While I appreciate the effort to create this issue, I don't think we need a meta issue. I like to keep issues actionable and a meta issue is by definition not actionable.

Besides, a section is only a specific type of block. AsciiDoc has quite a few type of blocks : 

- admonition
- sidebar
- paragraph
- list
- table
- section
- open, source, example, stem, quote, verse... blocks

Implementation wise, the tough part is that it depends on the context, for instance:

```
....
|====
| not a table
|====
....

|====
| a table
|====
```

I don't know what's the best strategy. In theory, we could Asciidoctor AST but the sourcemap feature isn't perfect (https://docs.asciidoctor.org/asciidoctor/latest/api/sourcemap/). Having said that, it might be good enough for now.
Another solution would be to implement a parser that accurately tracks source location of blocks. That would be a good exercise since I intend to implement a pure JavaScript parser of the AsciiDoc language but will surely require a good amount of time and effort.

Feel free to create dedicated issues for each block type with basic and edge cases and how the content should be folded for every cases.

**Comment by noraj** [comment]
- [ ]  #789
