### ISSUE TITLE
Custom stylesheet not loading

### ISSUE THREAD

**Issue by KLynn2019** [asciidoctor/asciidoctor-vscode#595]
## Description

The preview pane is unable to load our custom stylesheet.

## System Information

VSC information:
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

VSC extension version is 3.0.0 (pre-release)

## To Reproduce

Ensure the stylesheet is in the path specified in the Asciidoc > Preview: Style setting. (In my setup, the path is explicit, not relative.)

Open an AsciiDoc file. Open the preview. A message displays: "Could not load 'asciidoc.styles': [path to stylesheet]

Close VSC and reopen. The same file and preview pane display, but inside the preview pane, a message displays: "An error occurred while loading view: asciidoc.preview"

## Screenshots & Files

Stylesheet:
[vscode-asciidoc-preview.zip](https://github.com/asciidoctor/asciidoctor-vscode/files/9047112/vscode-asciidoc-preview.zip)

**Comment by Mogztter** [comment]
Could you please share the settings you are using? Especially the value of `asciidoc.styles`?
I cannot reproduce on Linux:

![image](https://user-images.githubusercontent.com/333276/177360332-1b523597-00c9-46ad-b0dc-aab677f5c507.png)

**Comment by KLynn2019** [comment]
@Mogztter None of these paths are working for me.

**Comment by Mogztter** [comment]
> None of these paths are working for me.

Make sure to close the preview and reopen it when you update preview settings.
Here's what I get:

[working.webm](https://user-images.githubusercontent.com/333276/177398407-10e826ef-7324-414a-9177-52a187f7faf9.webm)

**Comment by KLynn2019** [comment]
Yep...I did all of that and I'm still getting the error message.

**Comment by Mogztter** [comment]
🤔 I don't really know why it's not working on your machine.
Could you please "Toggle Developer Tools" from the "Help" menu? Then, go to the "Network" tab in the Chrome DevTools:

![image](https://user-images.githubusercontent.com/333276/177406309-c804e3ec-f343-434b-a98d-8b1242ded8f3.png)


Close the preview (if it was opened), and open it again. You should see a GET request to the custom stylesheet. The request URL might give us an hint.

**Comment by Mogztter** [comment]
As you can see, the request URL contains double front slashes `//`:

```
https://file+.vscode-resource.vscode-cdn.net/c%3A//Users//klynn//Documents//vscode-asciidoc-preview.css
```

Whereas mine is using single front slashes: `/`:

```
https://file+.vscode-resource.vscode-cdn.net/c:/Users/ggrossetie//Documents/GitHub/asciidoctor-vscode/test-workspace/vscode-asciidoc-preview.css
```

That's why the URL cannot be resolved.
Are you sure that you are using single slashes in your settings?

**Comment by KLynn2019** [comment]
I am now...but I'm still getting the same result.

![image](https://user-images.githubusercontent.com/51419423/177409044-bbbe662c-5a1b-4aa7-a14f-e97c5cd0b52b.png)

**Comment by Mogztter** [comment]
We are definitely making progress, this request URL looks better.

Could you please copy and paste the end of the URL (starting at `c%3A/...`) in a browser and see if it can be resolved?

**Comment by KLynn2019** [comment]
It's not resolving. This is bizarre...I can see the file in my folder...

If I replace %3A with a forward slash, it does resolve.

**Comment by Mogztter** [comment]
I was wrong, Chrome does not automatically convert `%3A` to `:`. I used "Copy value" and the `%3A` was automatically replaced when I paste the URL in the Chrome address bar.

It might be a security/trust issue. It seems that this file is not part of your workspace? I know that VS Code has implemented a Workspace Trust feature to allow/disallow some features.

You should click on "Manage" (gear icon) on the left menu bar, then "Manage Workspace Trust". Make sure that this folder is in the "Trusted Folders & Workspaces":

![tempsnip](https://user-images.githubusercontent.com/333276/177619473-a7e408d6-6049-46c7-b0df-1a99c6290216.png)

**Comment by KLynn2019** [comment]
No dice...

**Comment by Mogztter** [comment]
@KLynn2019 could you try relative a path (i.e., `../../file.css`)? Additionally, could you try to prefix your path by `file:///` (for instance, `file:///C:/path/to/file.css`)?

And also could use front slashes instead of back slashes?

**Comment by KLynn2019** [comment]
I have tried every configuration I can think of and it's still not working. So now I'm going to see if someone else on my team is free to test on their machine. We've got a release coming up so it may not be right away...but I'll report back.

**Comment by blackace72** [comment]
I am having a similar issue after switching to the pre-release version 3.0.1.
### Environment:
```
Version: 1.69.1 (Universal)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:51.333Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.4.0
```

In my header 1 section of my `testing_document.adoc`, I use `:highlightjs-theme: dracula` and I get a console error saying `(Error: Unable to resolve nonexistent file '/Users/foobar/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.1/media/highlightjs/styles/dracula.min.css')`

As for my general stylesheet path, in setting I used:
```plain
/Users/foobar/Documents/asciidoc_documents/documents/vscode_folder/testing_document.adoc
```
Which worked in the previous 2.9.8 version, but suddenly doesn't work. I have also tried relative paths with dots `.` but that didn't work either.

I have also made sure to entrust the workspace folder and each subfolder with `.adoc` files.

I believe this has something to do with the change with how internal `.adoc` files link. I switched to 3.0.1 from 2.9.8 because I wanted internal linking to work, and it does now!; but now it seems linking to local files using the header attribute `:highlighterjs-theme:` and/or the asciidoc setting 'asciidoc.styles' doesn't link properly.

The errors also show `https://file+.vscode-resource`[...]. I am not sure if this is how it's supposed to work in VSCode because it has a built in browser, but maybe important.

I will try to test more.

**Comment by Mogztter** [comment]
> In my header 1 section of my testing_document.adoc, I use :highlightjs-theme: dracula and I get a console error saying (Error: Unable to resolve nonexistent file '/Users/foobar/.vscode/extensions/asciidoctor.asciidoctor-vscode-3.0.1/media/highlightjs/styles/dracula.min.css')

The VS Code extension is now using Highlight.js 11. The dracula theme was moved to a subfolder named `base16`: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.6.0/build/styles/base16/

So you should use `:highlightjs-theme: base16/dracula`.

> Request URL: https://file+.vscode-resource.vscode-cdn.net/Users/foobar/Documents/asciidoc_documents/stylesheets/user_created/readthe_dracula_modified.css

Is the CSS file located in the same workspace? Could you please open the Dev Tools to debug the request and see which status code you get?

**Comment by blackace72** [comment]
The `:highlightjs-theme: base16/dracula` solved that part, and it shows the coloring in rendered preview!


The CSS file is not within the workspace, since the workspace only includes my `vscode_folder` in this directory tree, while the CSS sheet is outside of it:

```
.
├── documents
│   ├── asciidoc_files.code-workspace
│   └── vscode_folder
│       └── testing_document.adoc
└── stylesheets
    └── user_created
        └── readthe_dracula_modified.css

4 directories, 3 files
```

This is the error within `Dev Tools > Network > readthe_dracula_modified.css > Headers`:
```
General:
|--------|
Request URL: https://file+.vscode-resource.vscode-cdn.net/Users/foobar/Documents/asciidoc_documents/stylesheets/user_created/readthe_dracula_modified.css
Request Method: GET
Status Code: 401  (from service worker)
Referrer Policy: strict-origin-when-cross-origin


Response Headers:
|-------------------|
Content-Type: text/plain;charset=UTF-8


Request Headers:
|-----------------|
Provisional headers are shown

Referer
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.69.1 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
```

**Comment by blackace72** [comment]
I noticed something. Previously there was an option (in 2.9.8): `Asciidoc: Use_asciidoctor_js`. I unchecked it and if I open the JSON, it looks fine in editor (not greyed):
<img width="508" alt="image" src="https://user-images.githubusercontent.com/93956043/179397066-67f39ac8-6f7b-4c6a-93bc-a6e6b6df5639.png">

But when I switch to the new version, that option disappears, and this is what the JSON looks like:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/93956043/179397104-b284b5cd-b703-4977-88fe-eb601b95a29f.png">

Perhaps helpful?

**Comment by Mogztter** [comment]
Maybe VS Code cannot load resources outside of the current workspace using `https://file+.vscode-resource.vscode-cdn.net` protocol.
Could you please try to move the stylesheet in the same workspace as the AsciiDoc file and try again?

The `use_asciidoctor_js` option is deprecated since Asciidoctor.js is now the only option available (i.e., Asciidoctor CLI was dropped in 3.x).

**Comment by blackace72** [comment]
After putting the file within the workspace, specifically within `vscode_folder` and changing the settings to the new path, it is still not working.

However, I am apparently getting problems with the CSS itself, as VSCode is warning me:

`'-ms-text-size-adjust' is not supported by Chrome, Chrome Android, Edge, Firefox, Safari, Samsung Internet. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+, Samsung Internet 6.0+.`

`'-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari, Samsung Internet. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+, Samsung Internet 6.0+.`

So maybe the newer version has a more updated browser, and some CSS declarations are breaking the rendering?

**Comment by Mogztter** [comment]
So it seems to confirm that VS Code cannot load resources from outside the workspace using `https://file+.vscode-resource.vscode-cdn.net`.

I'm not sure if we want to continue to support that as we merely bypass the security model of VS Code... 🤔

**Comment by Mogztter** [comment]
Interesting, in both cases you are using an absolute path? `F:\Archive\Configurations\CSS\adoc-final.css`.

> When I preview a file that resides on a different partition than the CSS, I get an error message that warns me: "Could not load 'asciidoc.styles': {path}"

The message is really `Could not load 'asciidoc.styles': {path}` or does the `{path}` variable get correctly replaced?

> When I preview a file on the same partition, volume, as the CSS, but not the same folder, I see no pop-up error, but the preview ignores the CSS and uses the VScode one, rather than the default asciidoctor.css.

Probably because you are outside of the workspace. I'm not sure why we don't get the error message in this case. I will try to reproduce this issue.

> I can otherwise include files as usual, using relative paths.

The include directive relies on Asciidoctor.js to resolve and read files whereas stylesheet are loaded using VS Code API.

**Comment by silktrader** [comment]
> Interesting, in both cases you are using an absolute path? `F:\Archive\Configurations\CSS\adoc-final.css`.

Yes, that's the case. I store various CSS in a central folder. For the record, your Chrome/Firefox extension handles absolute paths fine.

> The message is really `Could not load 'asciidoc.styles': {path}` or does the `{path}` variable get correctly replaced?
 
The path gets replaced; `{path}` is my own addition to shorten the error message.

> The include directive relies on Asciidoctor.js to resolve and read files whereas stylesheets are loaded using VS Code API.

I understand, thanks. 

I fiddled around with workspaces:

If I create a workspace, trust it, _move the CSS to the workspace folder_ ... the preview will actually show up as expected, whether it's an absolute or relative path. That's not practical.

If I keep the CSS and .adoc in separate folders, but add both folders to the trusted workplace ... the preview won't show up with the CSS, specified with its absolute path.

This (User\settings.json):


` 
"extensions.supportUntrustedWorkspaces": {
    
    "asciidoctor.asciidoctor-vscode": {
      "supported": true,
      "version": "3.0.1"
    },
  }
`

... has no effects on the preview.

En tous cas, merci.

**Comment by Mogztter** [comment]
That's really valuable, thanks!
Does it change anything if you use forward slashes instead of blackslashes: `F:/Archive/Configurations/CSS/adoc-final.css`?

> If I keep the CSS and .adoc in separate folders, but add both folders to the trusted workplace ... the preview won't show up with the CSS, specified with its absolute path.

I'm pretty sure this case works fine on Linux/macOS...

Would you be kind enough to repeat those tests using the built-in Markdown extension? Since the code is heavily inspired by this extension I want to make sure that we didn't mess things up!

Thanks

**Comment by Mogztter** [comment]
An important note, the path is relative to the workspace directory. For instance:

```
.
├── doc
│   └── index.adoc
└── styles
    └── custom.css

2 directories, 2 files
```

The relative path should be: `./styles/custom.css` (and not `../styles/custom.css`)

**Comment by Mogztter** [comment]
> If I keep the CSS and .adoc in separate folders, but add both folders to the trusted workplace ... the preview won't show up with the CSS, specified with its absolute path.

I can confirm that it does not work on Linux as well.
The good news is that it's working on the Markdown extension so definitely something is wrong... 🐛
