### ISSUE TITLE
do not duplicate attributes on include suggestion

### ISSUE THREAD

**Issue by eiswind** [asciidoctor/asciidoctor-vscode#620]
In asciidoc.provider.ts

[  const globalVariableDefinitions = documentText.match(/:\S+:.*/g)](https://github.com/asciidoctor/asciidoctor-vscode/blob/b65f1c171ce828e71f784cfdf8c5f2bc6e429f66/src/providers/asciidoc.provider.ts#L69)

leads to duplicate entries in the suggestions when i define an attribute in the same file. 

```adoc
:srcdir: ../two

include::{srcdir}/
```

![Bildschirmfoto vom 2022-08-14 16-28-08](https://user-images.githubusercontent.com/1238044/184542145-72ef8a1c-e663-4d55-a0dd-c2375d302537.png)

and further down it appears again (coming from a different provider)

![Bildschirmfoto vom 2022-08-14 16-28-22](https://user-images.githubusercontent.com/1238044/184542149-18bb78bc-223d-4b05-8eab-21aafbe58357.png)

**Comment by Mogztter** [comment]
We should not use a regular expression. Instead, we should use Asciidoctor.js to parse the AsciiDoc document using the `header_only` option. Then, we can retrieve attributes using: `Document#getAttributes`

**Comment by Mogztter** [comment]
It might be because `attributeReferenceProvider` will return it as well: https://github.com/asciidoctor/asciidoctor-vscode/blob/b65f1c171ce828e71f784cfdf8c5f2bc6e429f66/src/features/attributeReferenceProvider.ts#L5

We should probably remove [const globalVariableDefinitions = documentText.match(/:\S+:.*/g)](https://github.com/asciidoctor/asciidoctor-vscode/blob/b65f1c171ce828e71f784cfdf8c5f2bc6e429f66/src/providers/asciidoc.provider.ts#L69).


I think we should revise our completion item providers to make sure that we don't return the same items more than once.

**Comment by eiswind** [comment]
That's the case. The duplicate comes from AttributeReferenceProvider.

**Comment by ggrossetie** [comment]
It should be better in the latest version. Feel free to open a new issue if we can improve it further.
