### ISSUE TITLE
How to Auto-Open Asciidoctor Preview

### ISSUE THREAD

**Issue by blueray453** [asciidoctor/asciidoctor-vscode#63]
For markdown there is "Markdown All in One" which enables automatic Markdown preview whenever you open new Markdown file, using `markdown.extension.preview.autoShowPreviewToSide`. I don't have to press `Ctrl+K V` everytime I open a markdown file.

Is there anything similar feature for .adoc files?

**Comment by joaompinto** [comment]
There is nothing at the moment, but should be added.

**Comment by joaompinto** [comment]
Closed with the release of v2.0.0

**Comment by JohnVeness** [comment]
Apologies for bumping this old issue, but I came here to ask for the same feature. As far as I can tell the current version (2.8.4) does not auto-open the preview, and I cannot see a setting for it to do so either.

I never used 2.0.0 so I don't know if that had such a feature.

Comments on issue #145 suggests that such a feature doesn't exist either, or at least not when that issue was opened.

Am I looking in the wrong place?
