### ISSUE TITLE
Exporting a PDF via the VSC extension ignores pdf-theme and pdf-themesdir

### ISSUE THREAD

**Issue by ioannisstavrakakis** [asciidoctor/asciidoctor-vscode#637]
Hello,

I have set the following attributes in the adoc header:

```
:pdf-theme: theme.yml
:pdf-themesdir: ../../styles
```

in order to execute the asciidoctor-pdf from Bash with as less variables as possible.

```
asciidoctor-pdf test.adoc -r asciidoctor-lists -a source-highlighter=coderay -r asciidoctor-diagram --trace

```

However, when exporting PDF through VSC, the asciidoctor-pdf seems to ignore those.
If I set them in the "Asciidoctor Pdf Command Args", it works, but only if I comment those attributes out in the adoc header.
![image](https://user-images.githubusercontent.com/87022642/189914392-cf9c1d89-f680-4aab-a968-e2753c3fe352.png)

If I do not set them in the  "Asciidoctor Pdf Command Args", it does not work.

Should the asciidoctor-pdf be able to read those from the adoc header, as it happens when I run the command in Bash?

Can I somehow have those attributes set in the adoc head and also to be able to export the PDF via VSC with the correct theme?

Thank you!

_Visual Studio Code_
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: **Windows_NT x64 10.0.19044**
Sandboxed: No

Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

Asciidoctor PDF 2.3.0 using Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x64-mingw-ucrt]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

AsciiDoc VSC extension
v3.0.1 pre-release

**Comment by Mogztter** [comment]
It might be a base directory issue. Could you please try to configure the path relative to the root? i.e.,`:pdf-theme: styles/theme.yml`

**Comment by Mogztter** [comment]
Having said that, we set the base directory using `path.dirname(docPath)`:

https://github.com/asciidoctor/asciidoctor-vscode/blob/f3690d83e3ab830079cb4667eb81dba62c925094/src/commands/exportAsPDF.ts#L57

Could you please share your directory structure?

**Comment by Mogztter** [comment]
> pdf-themesdir
The directory where the theme file is located. If the path is relative, the value is resolved starting from the current working directory. You can use the {docdir} token as the first path segment to create an absolute path starting from the directory of the document. Specifying an absolute path is recommended.

https://docs.asciidoctor.org/pdf-converter/latest/theme/apply-theme/#theme-and-font-directories

**Comment by Mogztter** [comment]
Asciidoctor PDF does not use the base directory to resolve relative themesdir path and recommend to use the `{docdir}` token as the first path segment to create an absolute path starting from the directory of the document.

**Comment by ioannisstavrakakis** [comment]
> Having said that, we set the base directory using `path.dirname(docPath)`:
> 
> https://github.com/asciidoctor/asciidoctor-vscode/blob/f3690d83e3ab830079cb4667eb81dba62c925094/src/commands/exportAsPDF.ts#L57
> 
> Could you please share your directory structure?

|_repo
 |_styles
  |_theme.yml
 |_guides
  |_config_guide
  |_test.adoc

**Comment by ioannisstavrakakis** [comment]
I solved it by removing the :pdf-themesdir: altogether, and setting the :pdf-theme: ../../styles/theme.yml.

Now I can use both the Export PDF from VSC functionality, as well as a lean bash Git bash command `asciidoctor-pdf test.adoc`, without any conflicts.

**Comment by Mogztter** [comment]
Did you use `{docdir}`?
If not sure it might be a bug because I would expect the following to be strictly equivalent:

```
:pdf-theme: theme.yml
:pdf-themesdir: ../../styles
```

```
:pdf-theme: ./../styles/theme.yml
``` 

But maybe not... 🤔 

@mojavelinux is there any difference between the two?

**Comment by mojavelinux** [comment]
Asciidoctor PDF resolves the `pdf-theme` relative to the `{docdir}` if `pdf-themesdir` is not specified. If you specify `pdf-themesdir`, then that value is going to be resolved relative to the current directory. If you want it to use a path relative to `{docdir}` instead, then you must use `{docdir}` as the first path segment in the `pdf-themesdir` value. See https://github.com/asciidoctor/asciidoctor-pdf/blob/394aa9507551295e1a25a4ae8864e776e9e3bfe0/lib/asciidoctor/pdf/converter.rb#L541 So yes, there is a difference. We may need some clarification in the docs.

> Asciidoctor PDF does not use the base directory to resolve relative themesdir path

The base dir is inadequately defined in Asciidoctor, which is why we don't rely on it here.

**Comment by mojavelinux** [comment]
> We may need some clarification in the docs.

I think the docs may actually be wrong. I will review them and make sure they are accurate.

**Comment by mojavelinux** [comment]
I have updated the documentation for pdf-theme, pdf-themesdir, and pdf-fontsdir to make it as clear as I can.

I can verify that the two settings are equivalent:

```
:pdf-theme: ../../styles/theme.yml
```

and

```
:pdf-theme: theme.yml
:pdf-themesdir: ../../styles
```

However, whether the theme file can be found very much depends on what the current working directory of the command. That's because the combined relative path is resolved starting from the current working directory. In order ot make it stable, so that it's relative to the directory of the source document instead, the value must start with `{docdir}`.

```
:pdf-theme: {docdir}/../../styles/theme.yml
```

or

```
:pdf-theme: theme.yml
:pdf-themesdir: {docdir}/../../styles
```

This assumes, of course, that `docdir` is actually set correctly, which it should be when invoking the `asciidoctor-pdf` command.

**Comment by ioannisstavrakakis** [comment]
Thank you both!
