### ISSUE TITLE
Double clicking the preview causes it to loose its position

### ISSUE THREAD

**Issue by aryzing** [asciidoctor/asciidoctor-vscode#715]
**What I'm trying to do**

Double click on the document preview to highlight a word or a phrase.

**What happened**

Double clicking causes the editor to reveal the source file, which is unexpected. Moreover, when returning to the preview, the scroll position is reset to the top of the document. Overall, this behavior results in the tedious process of accidentally double clicking > switching to the source file > going back to preview > finding scroll position at the time of double click, which breaks the reader's flow.

**What did I expect to happen**

Double clicking on a word or phrase should highlight it.

**Version**

```
AsciiDoc v2.9.8
```

[Screencast from 2023-05-09 09-22-21.webm](https://user-images.githubusercontent.com/4924405/237038466-41bab6c8-5dd0-4f95-a707-4f8e8e27d869.webm)

**Comment by ggrossetie** [comment]
Thanks for the detailed report.

> Double clicking causes the editor to reveal the source file

I was not aware of this "feature". It also exists in the Markdown extension but the line tracking is more accurate. When you double click, it will navigate to the source file on the corresponding line.
And since the "scroll position" is saved and restored on the preview it's actually a nice feature.


https://github.com/asciidoctor/asciidoctor-vscode/assets/333276/64085876-d6ca-48a0-9af1-f8e6e3ab7998

Having said that, I'm willing to disable this feature until we can properly support it.
