### ISSUE TITLE
"Follow link" not working

### ISSUE THREAD

**Issue by traits** [asciidoctor/asciidoctor-vscode#732]
VSCodes "Follow link" is not working, if applied when hovering an URL inside asciidoc source code (not the preview). Obviously, any link text (the part in brackets) is considered part of the URL and causes an 404 or similar. Example:

`https://github.com/asciidoctor/asciidoctor-vscode[Code Plugin]`

Code: v1.79.2
OS: Windows 10
Plugin: v2.9.8

**Comment by ggrossetie** [comment]
As far as I know, we currently do not provide this feature. This is a built-in feature of VS Code but you can disablethis feature for AsciiDoc file using `@lang:asciidoc editor.links` then uncheck the checkbox.

Not sure if an extension can automatically configure this option but that's what we will need to do if/when we implement this feature.

**Comment by ggrossetie** [comment]
Actually we can:

```
"configurationDefaults": {
  "[asciidoc]": {
    "editor.wordWrap": "on",
    "editor.quickSuggestions": false,
    "editor.links": false
  }
},
```

https://github.com/asciidoctor/asciidoctor-vscode/blob/45302b52a57c8e3ffdd37cdca3a4f7145df7be23/package.json#L574-L579

**Comment by ggrossetie** [comment]
I marked this issue as "good first" if you want to give it a try. The fix is to add `"editor.links": false` and then create a follow-up issue to properly implement this feature.

We should probably use this regular expression to find all the inline links: https://github.com/asciidoctor/asciidoctor/blob/be7356dafd3bdd82d9b515a59997da64f300eaf1/lib/asciidoctor/rx.rb#L522C3-L522C15
