### ISSUE TITLE
Inserts "appendix-caption" or "allow-uri-read" after open brace when you hit enter

### ISSUE THREAD

**Issue by danvk** [asciidoctor/asciidoctor-vscode#740]
When I type <kbd>{</kbd><kbd>Enter</kbd> in an Asciidoc file, I wind up with:

```
{allow-uri-read}
```

(with pre-release I wind up with `{appendix-caption}`)

I think this is some kind of suggestion or snippet gone awry?

Here's a video of what happens when I type `function foo(){` and then <kbd>Enter</kbd>:

https://github.com/asciidoctor/asciidoctor-vscode/assets/98301/076bcab9-5787-4c19-93cf-f497fc81a083

This happens both with the released version (v2.9.8) and the Pre-Release version. It happens in both code samples and in regular text. I'd love some way to at least disable this.

```
Version: 1.80.0 (Universal)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T13:39:33.766Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Comment by ggrossetie** [comment]
I think we should disable attribute completion in the following cases:

- One or more spaces at the start of the line (most likely a literal block)
- Inside a literal or source block (delimiters: `----`, `....` or ` ``` `)

**Comment by ggrossetie** [comment]
I would recommend to uncomment it when you are doing edits. The reason is that the content is non interpreted since it's a comment block. I've disabled this feature when the cursor is inside a "literal" block. Arguably, we could also disable this feature when the cursor is inside a comment block... 🤔 

Please open a new issue if you think we should disable attribute completion on comment blocks.
