### ISSUE TITLE
Export to PDF does not work on MacOS

### ISSUE THREAD

**Issue by cdroot92** [asciidoctor/asciidoctor-vscode#79]
Hi, I use vscode extension AsciiDoc 0.12.0

I can't install wkhtmltopdf when I do adoc.ExportAsPDF

I think you have to modify download_url in line 87 of ExportAsPDF.ts

now
const download_url = `https://github.com/joaompinto/asciidoctor-vscode/raw/master/wkhtmltopdf-bin/wkhtmltopdf-${platform}-${arch}${ext}.gz`
new
const download_url = `https://github.com/joaompinto/asciidoctor-vscode/wkhtmltopdf-bin/wkhtmltopdf-${platform}-${arch}${ext}.gz`

I want to use adoc.ExportAsPDF

**Comment by joaompinto** [comment]
What is your OS Version?

**Comment by cdroot92** [comment]
It's macOS

**Comment by joaompinto** [comment]
The current url at the source is ok, but right now there is no archive for mac because I have no experience with it. Right now do you get an error ? Does it provide the link that is failing to download ?

**Comment by cdroot92** [comment]
Now, I get an error

<img width="460" alt="screen shot 2018-05-03 at 9 31 19 pm" src="https://user-images.githubusercontent.com/8177403/39576574-8c37c312-4f19-11e8-8dc4-5ff185e181ff.png">

**Comment by moliyadi** [comment]
Same problem

**Comment by fcrespo82** [comment]
Hi. First thank you for the extension. Is a great one...

I think there is two ways we can solve this... 

1. Try with the binary that I extracted from the pkg of the official wkhtmltopdf site.
2. Instead of downloading on a macOS, find the binary at the path an use it if found. If not instruct to download and install from homebrew or official site. I'm making a homebrew package to install under Cellar and not outside as the current one do. (But this is a discussion for homebrew-core, not here)

I attached the file here for testing. In my machine it worked with it. I cloned the repo put the extracted file in `out/src` and exported a test file..

[wkhtmltopdf-darwin-x64.gz](https://github.com/joaompinto/asciidoctor-vscode/files/2417847/wkhtmltopdf-darwin-x64.gz)

**Comment by joaompinto** [comment]
@fcrespo82 thanks for the help, option 1) is the "standard" approach being used now, I was just missing feedback that it would work on Mac, I have aded wkhtmltopdf-darwin-x64.gz to the git folder so it should now be downloadabed.

@ravipinto The download wkhtmlpdf option that is automatically called by the extension should now work on Mac.

I'll leave the issues until getting a positive feedback about the change.

**Comment by ravipinto** [comment]
@joaompinto, I tested the download option and it is working as expected. Thanks for the update!

**Comment by joaompinto** [comment]
Closed with the release of v2.0.0
