### ISSUE TITLE
Overescaping of apostrophes in section headings

### ISSUE THREAD

**Issue by danvk** [asciidoctor/asciidoctor-vscode#794]
I'm not exactly sure what this line is called in VS Code (the breadcrumbs line?) but section headings look to be overescaping apostrophes. They should be shown as apostrophes (`'`), not `&#8217;`:

<img width="865" alt="image" src="https://github.com/asciidoctor/asciidoctor-vscode/assets/98301/2c24ee5d-8361-47dd-aa36-6c7f1067805e">

Name: AsciiDoc
Id: asciidoctor.asciidoctor-vscode
Description: Provides rich language support for AsciiDoc.
Version: 3.1.5
Publisher: asciidoctor
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode

Version: 1.82.2 (Universal)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by ggrossetie** [comment]
We also have this issue in the "Outline".
I think the reason is that we are calling `getTitle` on a `Section`:

https://github.com/asciidoctor/asciidoctor-vscode/blob/15b4562d6e834518b35ad1b12e4943035cf0fac3/src/tableOfContentsProvider.ts#L51


This function will apply substitutions, see: https://github.com/asciidoctor/asciidoctor/blob/880f043f4543da2d57c9834190192fff2ec97572/lib/asciidoctor/abstract_block.rb#L288-L291 

I guess it's important to apply subs so maybe we should still call `getTitle` but then replace HTML entities... 🤔 
@mojavelinux is that the best way to do it?

**Comment by mojavelinux** [comment]
It's often necessary to decode and reencode when extracting content out of an AsciiDoc document. This happens in several places in Asciidoctor PDF (such as when building the outline), so it's not abnormal.

If the information is being represented outside of the rendered document (in other words, outside of the preview pane), you have two options:

* clean all the tags
* keep the tags, but make sure nothing gets double encoded

I'm not sure what the requirements are for the context in which the title is being used. If it accepts HTML, then it should not be double encoding anything. If it does not accept HTML, but rather tries to encode it, then the value must be sanitized first.

**Comment by ggrossetie** [comment]
I'm doing the same in Asciidoctor Web PDF:  https://github.com/ggrossetie/asciidoctor-web-pdf/blob/3fe542a6de26a1862869fbca0178ec18a80ac42d/lib/outline.js#L6-L11
