### ISSUE TITLE
antora.yml search could be improved to avoid scanning the whole workspace

### ISSUE THREAD

**Issue by alexandruavadanii** [asciidoctor/asciidoctor-vscode#814]
Please provide details about:

* What you're trying to do
Use the extension in a large vscode workspace.

* Why you can't use this extension for this
Searching for `antora.yml` hogs too many resources.

* How you think this extension could handle this
Some ideas have been discussed in issue #809, e.g. https://github.com/asciidoctor/asciidoctor-vscode/issues/809#issuecomment-1788193721.

**Comment by ggrossetie** [comment]
For reference, we are looking for `antora.yml` on all workspaces because we want to build a "complete" content catalog.

Instead, what we could do is build a content catalog for the current documentation component. In other words, if I open an AsciiDoc file in `workspace/**/<dir>/modules/**/pages/**/**/file.adoc` or `workspace/**/<dir>/modules/**/partials/**/**/file.adoc`, the extension will try to read a YAML file at `workspace/**/<dir>/antora.yml`.

The only limitation is when the user has more than one documentation component in their workspaces. In this case, I don't see how we can automatically detect them without using a fuzzy glob search `**/antora.yml`.

We should probably introduce a settings (or a configuration file) where the user can define where the documentation components are located?

@mojavelinux any thoughts?

**Comment by ggrossetie** [comment]
It's important to note that we don't know for sure that the locally documentation components are part of the same documentation site. In other words, we might include unrelated documentation components in the content catalog.

**Comment by ggrossetie** [comment]
The IDEA extension relies on the Intellij search index so looking for `**/antora.yml` is relatively fast.
